capaon/apps/home/urls.py
from django.conf.urls.defaults import patterns,url

urlpatterns = patterns('capaon.apps.home.views',
	url(r'^$','index_view', name='vistaInicial'),
	url(r'^register/$','register_view', name = 'vista_registro'),
	url(r'^register/empresa$','registrar_empresa', name = 'vista_registro_empresa'),
	url(r'^register/individual$','registrar_individual', name = 'vista_registro_individual'),
	url(r'^MisionVision/$','mv_view', name = 'vista_MisionVision'),
	url(r'^capacitacion/$','cursos_view', name = 'vista_Cursos'),
	url(r'^capacitacion/(\d{1,2})$','Infocursos_view', name = 'vista_InfoCursos'),
	url(r'^capacitacion/(\d{1,2})/inscripcion$','inscripcion_view', name = 'vista_inscripcion'),
	url(r'^contacto/$','contact_view', name = 'vista_Contacto'),
	url(r'^search/$','search_view', name = 'vista_search'),
	url(r'^login/$','login_view', name = 'login'),
	url(r'^logout/$','logout_view', name = 'logout'),
	url(r'^miscursos/$','miscursos_view', name = 'miscursos'),
	url(r'^profile/$','profile_view', name = 'vista_perfil'),
	)

capaon/urls.py
from django.conf.urls import patterns, include, url
import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    #Se conecta con las url de la aplicacion home para mostrar la pagina inicial
    url(r'^',include('capaon.apps.home.urls')),
    #activar servidor de medios en carpeta media
    url(r'^media/(?P<path>.*)', 'django.views.static.serve', {'document_root':settings.MEDIA_ROOT}),

    # Administrador Django
    # administrar:
    url(r'^admin/', include(admin.site.urls)),

)

capaon/apps/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
import watson
import datetime

# Tuplas que son Utilizadas en los modelos de datos

pais = (('Colombia','colombia'), ('Venezuela','venezuela'),('Brasil','brasil'))
dias = (('Lunes','Lunes'),('Martes','Martes'),('Miercoles','Miercoles'),('Jueves', 'Jueves'),('Viernes','Viernes'),('Sabado', 'Sabado'),	('Domingo', 'Domingo'))
EstadoCurso = (('En curso','En curso'), ('En Inscripciones','En Inscripciones'),('Cancelado','Cancelado'),('Terminado','Teminado'))
cliente = (('Individual','Individual'),('Empresarial','Empresarial'))
estadoCliente = (('Inscrito','Inscrito'),('Matriculado','Matriculado'))


# En este modelo se agrega el contenido principal de la plataforma
# Entre ellos esta, Mision, Vision y Quienes Somos
class DatosEmpresa(models.Model):
	titulo 		= 	models.CharField(max_length=100, primary_key=True, help_text='Por favor,No edite este titulo')
	Contenido 	= 	models.TextField(help_text='Agregue el Contenido')

	class Meta:
		verbose_name_plural="Datos del home"
	def __unicode__(self):
		return self.titulo


# Este modelo contiene los datos de contacto de la Empresa
# Estos datos son mostrados en la seccion Contactame y en el pie de pagina de cada seccion
class Contacto(models.Model):
	empresa 	= 	models.CharField(max_length=100, primary_key=True, help_text='Nombre de la Empresa')
	pais 		= 	models.CharField(max_length=100, choices=pais)
	ciudad 		= 	models.CharField(max_length=100)
	telefono 	= 	models.CharField(max_length=50)
	email 		= 	models.EmailField(help_text='correo@example.com')

	class Meta:
		verbose_name_plural=u'Datos De Contacto Capaon'
	def __unicode__(self):
		return self.empresa


# Modelo para definir los horarios de los cursos
class Horario(models.Model):
	dia 	= 	models.CharField(max_length=40, choices = dias)
	de 		=	models.CharField(max_length=40,help_text='Escribe la hora ej: 2:00 p.m.')
	hasta 	= 	models.CharField(max_length=40,help_text='Escribe la hora ej: 2:00 p.m.')

	def __unicode__(self):
		return self.dia + " " + self.de + " a " + self.hasta



# Modelo para especificar el nombre y la descripcion del Facilitador de un curso
class Facilitador(models.Model):
	nombre 			= 	models.CharField(max_length=100, unique=True)
	descripcion 	= 	models.TextField(blank=True, help_text='Describa al Facilitador')

	class Meta:
		verbose_name_plural = "Facilitadores"
	def __unicode__(self):
		return self.nombre
	


class Curso(models.Model):
	nombre 				= 	models.CharField(max_length=100, unique=True, help_text='Nombre de Curso', null=False)
	generalidades 		= 	models.TextField()
	objetivos 			= 	models.TextField(help_text='Escriba cada objetivo separado por un salto de linea, si es subindice, agregue un guion')
	duracion 			= 	models.IntegerField(help_text="Horas. Ej: 12")
	horario 			= 	models.ManyToManyField(Horario, help_text='Asigne uno o varios horarios')
	metodologia 		=	models.TextField()
	estado 				= 	models.CharField(choices= EstadoCurso, max_length=50, blank=True)
	cupoMin 			= 	models.IntegerField(default=20)
	cupoMax 			= 	models.IntegerField(default=30)
	#cuposDisponible		=	models.IntegerField()
	inicioInscripciones = 	models.DateField(auto_now=True, help_text='Feha Inicial Para Inscripciones')
	finalInscripciones 	= 	models.DateField(help_text='Fecha Final para Inscripciones (La fecha de Inicio empieza al crear este curso)')
	fechaInicio 		= 	models.DateField(help_text='Fecha de Inicio de curso')
	fechaFinal 			= 	models.DateField(help_text='Fecha de Finalizacion de curso')

	def __unicode__(self):
		return self.nombre

# modelo para guardar los clientes que se han inscrito en alguno de los cursos ofertados
class Inscrito(models.Model):
	curso 				= 	models.ForeignKey(Curso, null=True)
	cliente 			= 	models.ForeignKey(User, help_text='Escoja un cliente de la lista', null=True)
	fechaInscripcion 	= 	models.DateField(auto_now_add=True,null=True)
	FechaCaducidad 		= 	models.DateField(null=True)

	def __unicode__(self):
		return self.cliente.get_profile().nombre + " " + self.cliente.get_profile().apellidos  


# modelo para guardar los clientes que se han matriculado en alguno de los cursos ofertados
class Matriculado(models.Model):
	curso 				= 	models.ForeignKey(Curso, null=True)
	cliente 			= 	models.ForeignKey(User, help_text='Escoja un cliente de la lista', null=True)
	fechaMatricula 		= 	models.DateField(auto_now_add=True)

	def __unicode__(self):
		return self.cliente.get_profile().nombre + " " + self.cliente.get_profile().apellidos  


class Modulo(models.Model):
	numero 		= 	models.IntegerField(help_text='Numero del modulo del curso')
	nombre 		= 	models.CharField(max_length=150, unique=True, help_text='Nombre del modulo')
	duracion 	=	models.IntegerField(help_text='Ingrese un entero con el valor de las horas de duracion ej: 25')
	facilitador = 	models.ForeignKey(Facilitador,null=True, help_text='Escoja un facilitador')
	contenido 	= 	models.TextField(help_text='Ingrese el contenido separando cada apartado con un salto de linea')
	curso 		= 	models.ForeignKey(Curso, help_text='Escoje el curso al cual pertenece este modulo')

	def __unicode__(self):
		return self.nombre


# Los modelos de Usuario Individual y Empresarial son iniciales y no se han optimizado
# Esta tarea se hara en el segundo release


class PerfilCliente(models.Model):
	user 			= 	models.ForeignKey(User, related_name='perfil', unique=True)
	nombre 			= 	models.CharField(max_length=50)
	apellidos 		= 	models.CharField(max_length=60)
	email 			= 	models.EmailField()
	cedula 			= 	models.CharField(max_length=100)
	direccion 		= 	models.CharField(max_length=100, blank=True)
	fechaNacimiento = 	models.DateField(null=True, blank=True)
	telefono 		=	models.CharField(max_length=30, blank=True)
	celular  		= 	models.CharField(max_length=100)
	ciudad 			= 	models.CharField(max_length=50, blank=True)
	pais 			= 	models.CharField(max_length=50, choices=pais)

	class Meta:
         verbose_name = "PerfilCliente"
	
	def __unicode__(self):
		return self.nombre + " " + self.apellidos

class Empresa(models.Model):	
	razonSocial 	= 	models.CharField(max_length=100)
	nit 			= 	models.CharField(max_length=100, primary_key=True)
	actividad 		= 	models.CharField(max_length=100)
	fax 			= 	models.CharField(max_length=30)
	representante 	= 	models.ForeignKey(PerfilCliente, unique=True)
	
	def __unicode__(self):
		return self.razonSocialcd

class Cliente(models.Model):
	perfil 		= 	models.ForeignKey(PerfilCliente, unique=True)
	tipo 		= 	models.CharField(max_length=50)
	potencial 	= 	models.BooleanField(default=False)

	class Meta:
		verbose_name_plural = "Definir Potenciales"

watson.register(DatosEmpresa)
watson.register(Horario)
watson.register(Curso)
watson.register(Modulo)

capaon/apps/home/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext 
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm 
from capaon.apps.home.models import DatosEmpresa, Contacto, Curso, Modulo, Empresa, PerfilCliente, Cliente, Inscrito, Matriculado
from capaon.apps.home.forms import ClienteForm, ContactForm, EmpresaForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.mail import send_mail
import watson
import datetime
from django.utils.timezone import is_aware, utc



#vista del index (pagina incial)
def index_view(request):
	loginInvalido = False;
	titulo = "Capacitaciones Online - CAPAON"
	quienesSomos = DatosEmpresa.objects.filter(titulo = 'Quienes Somos')
	contacto = Contacto.objects.all()
	cursos = Curso.objects.all()
	return render_to_response('index.html',locals(),context_instance = RequestContext(request))

#vista de Registro de Usuario
def register_view(request):
	if request.user.is_authenticated():
		return HttpResponseRedirect('/')
	contacto = Contacto.objects.all()
	return render_to_response('register.html', locals(), context_instance = RequestContext(request))

def registrar_empresa(request):
	if request.user.is_authenticated():
		return HttpResponseRedirect('/')
	contacto = Contacto.objects.all()
	if request.method == 'POST':
		cliente = ClienteForm(request.POST)
		empresaform = EmpresaForm(request.POST)
		if cliente.is_valid() and empresaform.is_valid():
			user = User.objects.create_user(username=cliente.cleaned_data['username'], email = cliente.cleaned_data['email'], password = cliente.cleaned_data['password'])
			user.first_name = cliente.cleaned_data['nombre'] 
			user.last_name = cliente.cleaned_data['apellidos']
			user.save()
			clienteEmpresa = PerfilCliente(user = user, nombre = cliente.cleaned_data['nombre'], apellidos = cliente.cleaned_data['apellidos'] , email = cliente.cleaned_data['email'],cedula = cliente.cleaned_data['cedula'], direccion = cliente.cleaned_data['direccion'], fechaNacimiento = cliente.cleaned_data['fechaNacimiento'], telefono = cliente.cleaned_data['telefono'], celular = cliente.cleaned_data['celular'], ciudad = cliente.cleaned_data['ciudad'],pais = cliente.cleaned_data['pais'])
			clienteEmpresa.save()
			empresa = Empresa(razonSocial = empresaform.cleaned_data['razonSocial'], nit = empresaform.cleaned_data['nit'], actividad = empresaform.cleaned_data['actividad'], fax = empresaform.cleaned_data['fax'], representante = clienteEmpresa)
			empresa.save()
			cliente = Cliente(perfil = clienteEmpresa, tipo = "Empresa")
			cliente.save()
			return  HttpResponseRedirect('/')
	else:		
		empresa = EmpresaForm()
		cliente = ClienteForm()
	return render_to_response('registroEmpresa.html', locals(), context_instance = RequestContext(request))

def registrar_individual(request):
	contacto = Contacto.objects.all()
	if request.user.is_authenticated():
		return HttpResponseRedirect('/')
	if request.method == 'POST':
		cliente = ClienteForm(request.POST)
		if cliente.is_valid():
			user = User.objects.create_user(username=cliente.cleaned_data['username'], email = cliente.cleaned_data['email'], password = cliente.cleaned_data['password'])
			user.first_name = cliente.cleaned_data['nombre'] 
			user.last_name = cliente.cleaned_data['apellidos']
			user.save()
			clienteIndividual = PerfilCliente(user = user, nombre = cliente.cleaned_data['nombre'], apellidos = cliente.cleaned_data['apellidos'] , email = cliente.cleaned_data['email'],cedula = cliente.cleaned_data['cedula'], direccion = cliente.cleaned_data['direccion'], fechaNacimiento = cliente.cleaned_data['fechaNacimiento'], telefono = cliente.cleaned_data['telefono'], celular = cliente.cleaned_data['celular'], pais = cliente.cleaned_data['pais'])
			clienteIndividual.save()
			cliente = Cliente(perfil = clienteIndividual, tipo = "Individual")
			cliente.save()
			return  HttpResponseRedirect('/')
	else:
		cliente = ClienteForm()
	return render_to_response('registroIndividual.html', locals(), context_instance = RequestContext(request))



#vista de mision y vision
def mv_view(request):
	Mision = DatosEmpresa.objects.filter(titulo = 'Mision')
	Vision = DatosEmpresa.objects.filter(titulo = 'Vision')
	contacto = Contacto.objects.all()
	return render_to_response('MisionVision.html', locals() , context_instance = RequestContext(request))

#Vista de la seccion Contactenos
def contact_view(request):
	contacto = Contacto.objects.all()
	if request.method =='POST':
		formulario = ContactForm(request.POST)
		if formulario.is_valid():
			titulo = "Mensaje Enviado desde CAPAON"
			contenido = formulario.cleaned_data['Mensaje'] + "\n"
			remitente = formulario.cleaned_data['Email']
			contenido += 'Comunicarse a: ' + remitente + "\n"
			contenido += 'Nombre de Remitente: ' + formulario.cleaned_data['Nombre'] + "\n"
			contenido += 'Ciudad: ' + formulario.cleaned_data['Ciudad']
			send_mail(titulo, contenido, remitente, ['elpipesalazar@hotmail.com'], fail_silently=False)	
			return HttpResponseRedirect('/')
	else:
		formulario = ContactForm()
	return render_to_response('contact.html',locals(),context_instance = RequestContext(request))

#Vista de la Seccion de Capacitacion
def cursos_view(request):
	cursos = Curso.objects.all()
	contacto = Contacto.objects.all()
	return render_to_response('cursos.html',locals(),context_instance = RequestContext(request))

def Infocursos_view(request, idn):
	try:
		contacto = Contacto.objects.all()
 		curso = Curso.objects.get(id = idn)
 		horario = curso.horario.all()
 		modulos = Modulo.objects.filter(curso__id__exact = idn)
 		if request.user.is_authenticated() and not request.user.is_staff:
 			estaInscrito = Inscrito.objects.filter(cliente = request.user)
 	except Curso.DoesNotExist:
 		curso = False
 	return render_to_response('infocurso.html',locals(), context_instance = RequestContext(request))



def inscripcion_view(request, idc):
	if request.user.is_authenticated() and not request.user.is_staff:
		fechaInscripcion = datetime.datetime.now(utc)
		fechaCaducidad = datetime.datetime(fechaInscripcion.year , fechaInscripcion.month, fechaInscripcion.day + 1)
		curso = Curso.objects.get(id__exact = idc)
		if curso:
			nuevoInscrito = Inscrito(curso = curso,cliente =request.user, fechaInscripcion = fechaInscripcion, FechaCaducidad = fechaCaducidad)
			nuevoInscrito.save()
			return HttpResponseRedirect('/miscursos/')
	return HttpResponseRedirect('/')


def miscursos_view(request):
	if request.user.is_authenticated() and not request.user.is_staff:
		misInscritos    = Inscrito.objects.filter(cliente = request.user)
		misMatriculados = Matriculado.objects.filter(cliente = request.user) 
		return render_to_response("miscursos.html", locals(), context_instance = RequestContext(request))
	return HttpResponseRedirect('/')
		



def construccion(request):
	return render_to_response('404.html', context_instance = RequestContext(request))

def search_view(request):
	search_results = watson.search('somos')
	return render_to_response('search.html', locals(), context_instance = RequestContext(request))

def login_view(request):
	try:
		nickname = request.POST['nickname']
		password = request.POST['password']
		usuario = authenticate(username=nickname, password=password)
		if usuario is not None and usuario.is_active:
			login(request,usuario)
			return HttpResponseRedirect('/')
	except:
		return HttpResponseRedirect('/')
	titulo = "Capacitaciones Online - CAPAON"
	loginInvalido = True;
	quienesSomos = DatosEmpresa.objects.filter(titulo = 'Quienes Somos')
	contacto = Contacto.objects.all()
	cursos = Curso.objects.all()
	return render_to_response('index.html',locals(),context_instance = RequestContext(request))


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

def profile_view(request):
	return render_to_response('perfil.html', context_instance = RequestContext(request))

capaon/templates/MisionVision.html
{% extends "base.html" %}
{% block titulo %}{{ titulo }}{% endblock %}
{% block clasem2 %}active{% endblock %}
{% block cuerpo %}
	<div class="tab-content" id="tab1">
	{% if Mision %}
		{% for n in Mision %}
			<div class="pad_bot2">
				<h5>{{ n.titulo }}</h5>
				<figure class="left marg_right1"><img src="/media/images/page2_img1.jpg" alt=""></figure>
				<p class="pad_bot1">{{ n.Contenido}}</p>
			</div>
		{% endfor %}
	{% else %}
		<p>Mision No definida aun</p>
	{% endif %}
	{% if Vision %}
		{% for m in Vision %}
			<div class="pad_bot2">
				<h5>{{ m.titulo }}</h5>
				<figure class="left marg_right1"><img src="/media/images/page2_img2.jpg" alt=""></figure>
				<p class="pad_bot1">{{ m.Contenido }}</p>
			</div>
		{% endfor %}
	{% else %}
		<p>Vision No definida aun</p>
	{% endif %}
	</div>
{% endblock %}
{% block datos %}
	{% if contacto %}
		{% for c in contacto  %}
			<h4>{{c.empresa}}</h4>
			<ul class="address">
				<li><span>País:</span>{{ c.pais }}</li>
				<li><span>Ciudad:</span>{{ c.ciudad }}</li>
				<li><span>Teléfono:</span>{{ c.telefono }}</li>
				<li><span>Email:</span><a href="mailto:">{{ c.email }}</a></li>
			</ul>
		{% endfor %}
	{% else %}
		<h4>datos no definidos</h4>
	{% endif %}
{% endblock datos %}

capaon/templates/contact.html
{% extends "base.html" %}
{% block titutlo %}Contáctanos{% endblock%}
{% block clasem4 %}active{% endblock %}
{% block cuerpo %}
<section class="col1">
	<h2 class="under">Formulario Contacto</h2>
	{% if formulario %}
		<form id="ContactForm" method="post" action="">
		{% csrf_token %}
		<div>
			<div  class="wrapper">
				<span>Tu Nombre:</span>
				{% for error in formulario.Nombre.errors%}
					<p class="error">{{error|escape}}</p>
				{% endfor %}
				{{ formulario.Nombre }}
			</div>
			<div  class="wrapper">
				<span>Tu Ciudad:</span>
				{% for error in formulario.Ciudad.errors%}
					<p class="error">{{error|escape}}</p>
				{% endfor %}
				{{ formulario.Ciudad }}
			</div>
			<div  class="wrapper">
				<span>Tu E-mail:</span>
				{{ formulario.Email}}
				{% for error in formulario.Email.errors%}
					<p class="error">{{error|escape}}</p>
				{% endfor %}
			</div>
			<div  class="textarea_box">
				<span>Tu Mensaje:</span>
				{{ formulario.Mensaje }}
			</div>
			<input type="submit" value="Enviar" class="submit">
			<a href="" onClick="document.getElementById('ContactForm').reset()">Limpiar</a>
		</div>	
	{% endif %}
	
</form>
</section>
<section class="col2 pad_left1">
	<h2 class="under">Contacto</h2>
	{% if contacto %}
		{% for d in contacto %}
	<div id="address"><span>Pais:<br>
			Ciudad:<br>
			Telefono:<br>
			Email:</span>
			{{d.pais}}<br>
			{{d.ciudad}}<br>
			{{d.telefono}}<br>
			<a href="mailto:" class="color2">{{d.email}}</a></div>
		{% endfor %}
	{% else %}
		Datos no definidos aun
	{% endif %}
</section>
{% endblock %}
{% block datos %}
	{% if contacto %}
		{% for c in contacto  %}
			<h4>{{c.empresa}}</h4>
			<ul class="address">
				<li><span>País:</span>{{ c.pais }}</li>
				<li><span>Ciudad:</span>{{ c.ciudad }}</li>
				<li><span>Teléfono:</span>{{ c.telefono }}</li>
				<li><span>Email:</span><a href="mailto:">{{ c.email }}</a></li>
			</ul>
		{% endfor %}
	{% else %}
		<h4>datos no definidos</h4>
	{% endif %}
{% endblock datos %}

capaon/templates/cursos.html
{% extends "base.html" %}
{% block titulo %}{{ titulo }}{% endblock %}
{% block clasem3 %}active{% endblock %}
{% block cuerpo %}
	{% if cursos %}
		{% for c in cursos  %}
		<section>
			<div>
				<h3><span class="dropcap">{{ forloop.counter }}</span>{{ c.nombre }}</h3>
				<figure><img src="/media/images/page4_img{{forloop.counter}}.jpg" alt=""></figure><br>
				<p class="pad_bot1">{{ c.generalidades}}</p>
				<h3>Inscripciones Hasta</h3> <p class="pad_bot1">{{ c.finalInscripciones }}</p><br>
				<a href="{{c.id}}" class="link1">Saber Más</a>
			</div>
		{% endfor %}	
	{% else %}
		<h2>Contenido sin definir</h2>				
	{% endif %}	
		
{% endblock %}
{% block datos %}
	{% if contacto %}
		{% for c in contacto  %}
			<h4>{{c.empresa}}</h4>
			<ul class="address">
				<li><span>País:</span>{{ c.pais }}</li>
				<li><span>Ciudad:</span>{{ c.ciudad }}</li>
				<li><span>Teléfono:</span>{{ c.telefono }}</li>
				<li><span>Email:</span><a href="mailto:">{{ c.email }}</a></li>
			</ul>
		{% endfor %}
	{% else %}
		<h4>datos no definidos</h4>
	{% endif %}
{% endblock datos %}

capaon/templates/miscursos.html
{% extends "base.html" %}
{% block clasem5 %}active{% endblock clasem5%}
{% block cuerpo %}
	<section id="inscritos">	
		<h3>Cursos Inscritos</h3>
		{% if misInscritos %}
			<p>No olvides Matricularte antes de la fecha de caducidad de tu inscripcion <br>Si no lo haces, perderás el cupo en el curso y deberás inscribirte de nuevo (Si aún hay cupos o si el curso está en fecha de inscipciones)</p>
			{% for c in misInscritos  %}
				<div>
					<h3><span class="dropcap">{{ forloop.counter }}</span>{{ c.curso.nombre }}</h3>
					<figure><img src="/media/images/page4_img{{forloop.counter}}.jpg" alt=""></figure><br>
					<p class="pad_bot1">{{ c.curso.generalidades}}</p> <br>
					<h3>Matrícula Hasta  </h3> <p class="pad_bot1">{{ c.FechaCaducidad }}</p>
					<a href="{{c.id}}" class="link1">Ver info del curso</a>
					<a class="boton">Matricularme</a> 
				</div>
			{% endfor %}	
		{% else %}
			<h3>No tienes Cursos Inscritos Aún</h3>
		{% endif %}	
	</section>
	<section id="matriculados">
		<h3>Cursos Matriculados</h3>
		{% if misMatriclados %}
		{% else %}
			<h3>No tienes Cursos matriculados Aún</h3>	
		{% endif %}
	</section>
{% endblock cuerpo %}

capaon/templates/registroEmpresa.html
{% extends "base.html" %}
{% block scripts %}
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js" type="text/javascript"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.js" type="text/javascript"></script>
        <script>
        $(function() {
            $( "#id_fechaNacimiento" ).datepicker({
 				yearRange: "1970:2012",
 				changeMonth: true,
            	changeYear: true 
            });
             $('#id_fechaNacimiento').datepicker('option', {dateFormat: 'dd/mm/yy'});
        });
        </script>
{% endblock scripts %}
{% block titulo %}Registro de Cliente Empresa {% endblock %}
{% block registrosesion %}{% endblock registrosesion %}
{% block cuerpo%}
	<section class="contRegistro">
		<section id="contEmpresarial">
			<h2>Usuario Empresarial</h2>
			<form action="" method=	"POST">
				{% csrf_token %}
					<h6>Datos del Representante legal</h6><br>
						{{ usuario.as_p }}
						{{ cliente.as_p }}
					<h6>Datos de la Empresa</h6>
						{{ empresa.as_p }}
					<input type="submit" value="Registrarse" class="boton">
			</form>
		</section>
	</section>
{% endblock %}
{% block datos %}
	{% if contacto %}
		{% for c in contacto  %}
			<h4>{{c.empresa}}</h4>
			<ul class="address">
				<li><span>País:</span>{{ c.pais }}</li>
				<li><span>Ciudad:</span>{{ c.ciudad }}</li>
				<li><span>Teléfono:</span>{{ c.telefono }}</li>
				<li><span>Email:</span><a href="mailto:">{{ c.email }}</a></li>
			</ul>
		{% endfor %}
	{% else %}
		<h4>datos no definidos</h4>
	{% endif %}
{% endblock datos %}

capaon/templates/registroIndividual.html
{% extends "base.html" %}
{% block scripts %}
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js" type="text/javascript"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.js" type="text/javascript"></script>
        <script>
        $(function() {
            $( "#id_fechaNacimiento" ).datepicker({
 				yearRange: "1970:2012",
 				changeMonth: true,
            	changeYear: true 
            });
             $('#id_fechaNacimiento').datepicker('option', {dateFormat: 'dd/mm/yy'});
        });
        </script>
{% endblock scripts %}
{% block titulo %}Registro de Cliente Individual {% endblock %}
{% block registrosesion %}{% endblock registrosesion %}
{% block cuerpo%}
	<section class="contRegistro">
		<section id="contEmpresarial">
			<h2>Usuario Individual</h2>
			<form action="" method=	"POST">
				{% csrf_token %}
					<h6>Tus datos Personales</h6><br>
						{{ cliente.as_p }}
					<input type="submit" value="Registrarse" class="boton">
			</form>
		</section>
	</section>
{% endblock %}
{% block datos %}
	{% if contacto %}
		{% for c in contacto  %}
			<h4>{{c.empresa}}</h4>
			<ul class="address">
				<li><span>País:</span>{{ c.pais }}</li>
				<li><span>Ciudad:</span>{{ c.ciudad }}</li>
				<li><span>Teléfono:</span>{{ c.telefono }}</li>
				<li><span>Email:</span><a href="mailto:">{{ c.email }}</a></li>
			</ul>
		{% endfor %}
	{% else %}
		<h4>datos no definidos</h4>
	{% endif %}
{% endblock datos %}